server:
  port: 9999
spring:
  dubbo:
    application:
      name: 004-registry-dubbo-provide
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan:
      base-packages: com.cib.dubbo